### ISSUE TITLE
load-balance doesn't eval in eos_switchconfig

### ISSUE THREAD

**Issue by tcyrus** [arista-eosplus/puppet-eos#141]
Using this example puppet config `example2.pp`:
```
$running_config = @(END)
! ...
load-balance policies
   load-balance fm6000 profile LB-7
      fields mac dst-mac vlan-priority
      fields ip protocol src-ip
      distribution symmetric-hash mac-ip
! ...
end
END

eos_switchconfig { 'running-config':
  content => $running_config,
}
```

```
-bash-4.3# puppet apply example2.pp --trace
...
Error: /Stage[main]/Main/Eos_switchconfig[running-config]: Could not evaluate:
>    load-balance fm6000 profile LB-7

% Invalid input at line 6
% Configuration replace aborted due to errors in loading the file

/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/errors.rb:106:in `fail'
/opt/puppetlabs/puppet/modules/eos/lib/puppet/provider/eos_switchconfig/default.rb:103:in `rescue in flush'
/opt/puppetlabs/puppet/modules/eos/lib/puppet/provider/eos_switchconfig/default.rb:87:in `flush'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1006:in `flush'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:25:in `evaluate'
...
```

Note: The only way to encounter this issue is by first solving #140.

**Comment by tcyrus** [comment]
This seems like a hardware issue, Closing
